// <auto-generated />
namespace SamuelNFCApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class convertcitytostring : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(convertcitytostring));
        
        string IMigrationMetadata.Id
        {
            get { return "202106281323433_convert-city-to-string"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
